services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    Nanbando\Console\Application:
        class: Nanbando\Console\Application
    Nanbando\Host\HostRegistry:
        class: Nanbando\Host\HostRegistry
    Nanbando\Client\ClientFactory:
        class: Nanbando\Client\ClientFactory
    Nanbando\Process\ProcessFactory:
        class: Nanbando\Process\ProcessFactory
    Nanbando\Task\TaskRegistry:
        class: Nanbando\Task\TaskRegistry
    Nanbando\Console\TaskCommandFactory:
        class: Nanbando\Console\TaskCommandFactory

    # Backup
    Nanbando\Filesystem\FilesystemFactory:
        class: Nanbando\Filesystem\FilesystemFactory
    Nanbando\Backup\BackupTaskCollection:
        class: Nanbando\Backup\BackupTaskCollection

    # Storage
    Nanbando\Storage\StorageRegistry:
        class: Nanbando\Storage\StorageRegistry
    Nanbando\Storage\StorageCommunicator:
        class: Nanbando\Storage\StorageCommunicator

    # Symfony console
    Symfony\Component\Console\Input\ArgvInput:
        class: Symfony\Component\Console\Input\ArgvInput
    Symfony\Component\Console\Output\ConsoleOutput:
        class: Symfony\Component\Console\Output\ConsoleOutput
    Symfony\Component\Console\Output\OutputInterface:
        alias: Symfony\Component\Console\Output\ConsoleOutput
    Symfony\Component\Console\Input\InputInterface:
        alias: Symfony\Component\Console\Input\ArgvInput
