services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    Nanbando\Host\HostRegistry:
        class: Nanbando\Host\HostRegistry
    Nanbando\Client\ClientFactory:
        class: Nanbando\Client\ClientFactory
    Nanbando\Process\ProcessFactory:
        class: Nanbando\Process\ProcessFactory
    Nanbando\Task\TaskRegistry:
        class: Nanbando\Task\TaskRegistry
